# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    templating.helper.assets: '@assets.packages'
    templating.helper.router: '@router'
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    
    form_extention.form_icon:
        class: AppBundle\Form\Extension\FormTypeIconExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }
    form_extention.button_icon:
        class: AppBundle\Form\Extension\ButtonTypeIconExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\ButtonType }
            
    validator.node.is_article_tag_assignment_unique:
        class: AppBundle\Validator\Constraints\IsArticleTagAssignmentUniqueValidator
        arguments: ['@doctrine']
        tags:
            - { name: validator.constraint_validator, alias: is_article_tag_assignment_unique }