# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    templating.helper.assets: '@assets.packages'
    templating.helper.router: '@router'
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    
    
    # Validators
    validator.node.is_article_tag_assignment_unique:
        class: AppBundle\Validator\Constraints\IsArticleTagAssignmentUniqueValidator
        arguments: ['@doctrine']
        tags:
            - { name: validator.constraint_validator, alias: is_article_tag_assignment_unique }
            
            
    # Voters 
    app.user_voter:
        class: AppBundle\Security\Base\UserVoter
        tags:
            - { name: security.voter }
        public: false
    
    # Twig extensions    
    twig.extension.value_sets:
        class: AppBundle\Twig\Extension\ValueSetsExtension
        tags:
            - { name: 'twig.extension' }
        
    # Form extensions          
    form_extension.form_icon:
        class: AppBundle\Form\Extension\FormTypeIconExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }
    form_extension.button_icon:
        class: AppBundle\Form\Extension\ButtonTypeIconExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\ButtonType }
            
            
    # Forms        
    app.form.registration:
        class: AppBundle\Form\Registration\UserRegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
            
            
    # Editors
    app.form.editor.advert_category_assignment:
        class: AppBundle\Form\Editor\Assignments\AdvertCategoryAssignmentEditorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
    app.form.editor.article_article_category_assignment:
        class: AppBundle\Form\Editor\Assignments\ArticleArticleCategoryAssignmentEditorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
    app.form.editor.article_brand_assignment:
        class: AppBundle\Form\Editor\Assignments\ArticleBrandAssignmentEditorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
    app.form.editor.article_category_assignment:
        class: AppBundle\Form\Editor\Assignments\ArticleCategoryAssignmentEditorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
    app.form.editor.article_tag_assignment:
        class: AppBundle\Form\Editor\Assignments\ArticleTagAssignmentEditorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
    app.form.editor.branch_category_assignment:
        class: AppBundle\Form\Editor\Assignments\BranchCategoryAssignmentEditorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
    app.form.editor.brand_category_assignment:
        class: AppBundle\Form\Editor\Assignments\BrandCategoryAssignmentEditorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
    app.form.editor.magazine_branch_assignment:
        class: AppBundle\Form\Editor\Assignments\MagazineBranchAssignmentEditorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
    app.form.editor.magazine_category_assignment:
        class: AppBundle\Form\Editor\Assignments\MagazineCategoryAssignmentEditorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
    app.form.editor.menu_entry_branch_assignment:
        class: AppBundle\Form\Editor\Assignments\MenuEntryBranchAssignmentEditorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
    app.form.editor.menu_entry_category_assignment:
        class: AppBundle\Form\Editor\Assignments\MenuEntryCategoryAssignmentEditorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
    app.form.editor.menu_menu_entry_assignment:
        class: AppBundle\Form\Editor\Assignments\MenuMenuEntryAssignmentEditorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
    app.form.editor.newsletter_block_advert_assignment:
        class: AppBundle\Form\Editor\Assignments\NewsletterBlockAdvertAssignmentEditorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
    app.form.editor.newsletter_block_article_assignment:
        class: AppBundle\Form\Editor\Assignments\NewsletterBlockArticleAssignmentEditorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
    app.form.editor.newsletter_block_magazine_assignment:
        class: AppBundle\Form\Editor\Assignments\NewsletterBlockMagazineAssignmentEditorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
    app.form.editor.newsletter_user_newsletter_group_assignment:
        class: AppBundle\Form\Editor\Assignments\NewsletterUserNewsletterGroupAssignmentEditorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
    app.form.editor.product_category_assignment:
        class: AppBundle\Form\Editor\Assignments\ProductCategoryAssignmentEditorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
    app.form.editor.term_category_assignment:
        class: AppBundle\Form\Editor\Assignments\TermCategoryAssignmentEditorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
            
            
    app.form.editor.article:
        class: AppBundle\Form\Editor\Main\ArticleEditorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
    app.form.editor.benchmark_field:
        class: AppBundle\Form\Editor\Main\BenchmarkFieldEditorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
    app.form.editor.category:
        class: AppBundle\Form\Editor\Main\CategoryEditorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
    app.form.editor.magazine:
        class: AppBundle\Form\Editor\Main\MagazineEditorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
    app.form.editor.menu_entry:
        class: AppBundle\Form\Editor\Main\MenuEntryEditorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
    app.form.editor.newsletter_block:
        class: AppBundle\Form\Editor\Main\NewsletterBlockEditorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
    app.form.editor.newsletter_page:
        class: AppBundle\Form\Editor\Main\NewsletterPageEditorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
    app.form.editor.product:
        class: AppBundle\Form\Editor\Main\ProductEditorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }

    # Others
    app.form.article_tag_assignments:
        class: AppBundle\Form\Other\ArticleTagAssignmentsType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }    
            
    app.form.send_newsletter_filter:
        class: AppBundle\Form\Filter\Admin\Other\SendNewsletterFilterType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }      
            
    app.form.import_newsletter_users:
        class: AppBundle\Form\Other\ImportNewsletterUsersType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }      
            
    # Benchmark        
    app.benchmark.category_filter:
        class: AppBundle\Form\Benchmark\CategoryFilterType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
    app.benchmark.subcategory_filter:
        class: AppBundle\Form\Benchmark\SubcategoryFilterType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
    app.benchmark.product_filter:
        class: AppBundle\Form\Benchmark\ProductFilterType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
            
    # Washers //TODO change to one common Product filter
    app.benchmark.washer_filter:
        class: AppBundle\Form\Benchmark\Washer\WasherFilterType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
    app.benchmark.centrifuge_filter:
        class: AppBundle\Form\Benchmark\Washer\CentrifugeFilterType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
    app.benchmark.washer_centrifuge_filter:
        class: AppBundle\Form\Benchmark\Washer\WasherCentrifugeFilterType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }