imports:
    - { resource: services/persistence_services.yml }
    - { resource: services/transaction_services.yml }
    - { resource: services/controller_services.yml }
    - { resource: services/factory_services.yml }
    - { resource: services/form_services.yml }
    - { resource: services/manager_services.yml }
    - { resource: services/repository_services.yml }
    - { resource: services/transformer_services.yml }
    - { resource: services/import_services.yml }
    - { resource: services/misc/provider_services.yml }
    - { resource: services/decorator_services.yml }
    - { resource: services/logic_services.yml }
    - { resource: services/command_services.yml }
    - { resource: services/utils_services.yml }

# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    templating.helper.assets: '@assets.packages'
    templating.helper.router: '@router'
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    
    
    # Validators
    validator.node.is_article_tag_assignment_unique:
        class: AppBundle\Validator\Constraints\IsArticleTagAssignmentUniqueValidator
        arguments: ['@doctrine']
        tags:
            - { name: validator.constraint_validator, alias: is_article_tag_assignment_unique }
            
            
    # Voters 
    app.user_voter:
        class: AppBundle\Security\Base\UserVoter
        tags:
            - { name: security.voter }
        public: false
        
    # Form extensions          
    form_extension.form_icon:
        class: AppBundle\Form\Extension\FormTypeIconExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }
    form_extension.button_icon:
        class: AppBundle\Form\Extension\ButtonTypeIconExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\ButtonType }
            
    # Twig extensions
    twig.extension.clean_name:
        class: AppBundle\Utils\StringUtils
        tags:
            - { name: 'twig.extension' }
    
    # Utils
    AppBundle\Utils\RegexUtils: ~
    AppBundle\Utils\Entity\BenchmarkFieldUtils:
        arguments:
            - '@AppBundle\Utils\Entity\DataBase\BenchmarkFieldDataBaseUtils'
    AppBundle\Utils\Entity\DataBase\BenchmarkFieldDataBaseUtils: ~
    
    # Repository Managers
    AppBundle\Repository\Factory\CommonRepositoryFactory:
        arguments:
            - '@doctrine.orm.default_entity_manager'
    AppBundle\Repository\Factory\AdminRepositoryFactory:
        arguments:
            - '@doctrine.orm.default_entity_manager'
    AppBundle\Repository\Factory\BenchmarkRepositoryFactory:
        arguments:
            - '@doctrine.orm.default_entity_manager'
    AppBundle\Repository\Factory\InfomarketRepositoryFactory:
        arguments:
            - '@doctrine.orm.default_entity_manager'
    AppBundle\Repository\Factory\InfoproduktRepositoryFactory:
        arguments:
            - '@doctrine.orm.default_entity_manager'
            
    # FormBuilders
    AppBundle\Form\FormBuilder\BenchmarkEditorFieldBuilder:
        arguments: ['@AppBundle\Form\Transformer\NumberToBooleanTransformer']
        tags:
            - { name: form.builder }
    AppBundle\Form\FormBuilder\BenchmarkFilterFieldBuilder:
        tags:
            - { name: form.builder }
            
    # Validation
    AppBundle\Validator\Base\BaseValidator:
        arguments:
            - '@validator'
            - '@translator'
    AppBundle\Validation\:
        resource: '../../src/AppBundle/Validation/*'
                    
    # Washers //TODO change to one common Product filter
    app.benchmark.washer_filter:
        class: AppBundle\Form\Benchmark\Washer\WasherFilterType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
    app.benchmark.centrifuge_filter:
        class: AppBundle\Form\Benchmark\Washer\CentrifugeFilterType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }
    app.benchmark.washer_centrifuge_filter:
        class: AppBundle\Form\Benchmark\Washer\WasherCentrifugeFilterType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }