services:
    # Common Factories
    AppBundle\Factory\:
        resource: '../../../src/AppBundle/Factory/*'

    # Entity Choices Factories   
    AppBundle\Factory\Common\Choices\Enum\:
        resource: '../../../src/AppBundle/Factory/Common/Choices/Enum/*'
        tags: [twig.extension]
                
    AppBundle\Factory\Common\Message\LifecycleMessageFactory:
        arguments:
            - '@translator'
            
    AppBundle\Factory\Admin\Import\NewsletterUser\ImportErrorFactory:
        arguments:
            - '@translator'
            
    AppBundle\Factory\Admin\Import\NewsletterUser\PreparedEntryFactory:
        arguments:
            - '@AppBundle\Factory\Admin\Import\NewsletterUser\ImportErrorFactory'
            - '@AppBundle\Validation\MailValidation'