AppBundle\Entity\BenchmarkField:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [category, fieldType, valueNumber]
            errorPath: category
            ignoreNull: false
            message: 'benchmarkField.unique'
                