AppBundle\Entity\BrandCategoryAssignment:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [brand, segment, category]
            ignoreNull: false
            message: 'brandCategoryAssignment.unique'
                