AppBundle\Entity\MagazineBranchAssignment:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [magazine, branch]
            ignoreNull: false
            message: 'magazineBranchAssignment.unique'
                