AppBundle\Entity\Main\Article:
    properties:
        page:
            - Range:
                min: 1
                max: 99
        orderNumber:
            - Range:
                min: 0
                max: 99   
    constraints:
        - Callback: validate