AppBundle\Entity\Main\Article:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [name, subname]
            errorPath: name
            ignoreNull: false
        - Callback: validate
    properties:
        name:
            - NotBlank: ~
        page:
            - Range:
                min: 1
                max: 99
        orderNumber:
            - Range:
                min: 0
                max: 99