AppBundle\Entity\MenuMenuEntryAssignment:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [menu, menuEntry]
            ignoreNull: false
            message: 'menuMenuEntryAssignment.unique'
                