AppBundle\Entity\Segment:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        name:
            - NotBlank: ~
        style:
            - NotBlank: ~
        content:
            - NotBlank: ~