AppBundle\Entity\User:
    properties:
        forename:
            - NotBlank: ~
            - Regex:
                pattern: '/^[^0-9!@#$%^&*(),.<>;:]+$/'
        surname:
            - NotBlank: ~
            - Regex:
                pattern: '/^[^0-9!@#$%^&*(),.<>;:]+$/'
        street:
            - NotBlank: ~
        zipCode:
            - NotBlank: ~
            - Regex:
                pattern: '/^\d{2}(?:[-\s]\d{3})$/'
        city:
            - NotBlank: ~
            - Regex:
                pattern: '/^[^0-9!@#$%^&*(),.<>;:]+$/'